services:
  redis:
    image: redis:8.0.2
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    restart: on-failure
    ports:
      - "8080:80"
    environment:
      API_PORT: 80
      REDIS_URL: redis://redis:6379/0
volumes:
  redis_data:
